CREATE DATABASE IF NOT EXISTS BD_ALUGUEL;
USE BD_ALUGUEL; 

CREATE TABLE IF NOT EXISTS CLIENTE(
	CLI_ID			INT AUTO_INCREMENT PRIMARY KEY,
    CLI_NOME		VARCHAR(50) NOT NULL,
    CLI_CPF			VARCHAR(11) not null,
	CLI_EMAIL		VARCHAR(50) NOT NULL,
    CLI_TELEFONE 	VARCHAR(9) NOT NULL
);

ALTER TABLE CLIENTE
MODIFY COLUMN CLI_CPF VARCHAR(11) NOT NULL UNIQUE;

CREATE TABLE IF NOT EXISTS PRODUTO(
	PRO_ID				INT AUTO_INCREMENT PRIMARY KEY,
    PRO_NOME			VARCHAR(50) NOT NULL,
    PRO_DESCRICAO		VARCHAR(200),
    PRO_PRECO			DOUBLE NOT NULL,
    PRO_QTD_DISPONIVEL 	INT NOT NULL
);

CREATE TABLE IF NOT EXISTS ALUGUEL(
	ALU_ID					INT AUTO_INCREMENT PRIMARY KEY,
    ALU_DATA_ALUGUEL		DATE NOT NULL,
    ALU_DATA_DEVOLUCAO 		DATE NOT NULL,
    ALU_VALOR_TOTAL 		DOUBLE NOT NULL,
    FK_CLI_ID				INT,
    FOREIGN KEY (FK_CLI_ID) REFERENCES CLIENTE(CLI_ID)
);

CREATE TABLE IF NOT EXISTS ALUGUEL_PRODUTO(
	ALP_ID 		INT AUTO_INCREMENT PRIMARY KEY,
    FK_PRO_ID 	INT NOT NULL,
    FK_ALU_ID	INT NOT NULL,
    FOREIGN KEY (FK_PRO_ID) REFERENCES PRODUTO(PRO_ID),
    FOREIGN KEY (FK_ALU_ID) REFERENCES ALUGUEL(ALU_ID)
);

INSERT INTO CLIENTE (CLI_NOME, CLI_CPF, CLI_EMAIL, CLI_TELEFONE)
VALUES ("Nicoli", "64186615080", "nicoli@email.com", "289420467");

INSERT INTO CLIENTE (CLI_NOME, CLI_CPF, CLI_EMAIL, CLI_TELEFONE)
VALUES ("Helena", "25186515980", "helena@email.com", "159875234");

INSERT INTO CLIENTE (CLI_NOME, CLI_CPF, CLI_EMAIL, CLI_TELEFONE)
VALUES ("Ana Silva", "12345678900", "ana.silva@example.com", "987654321");

INSERT INTO CLIENTE (CLI_NOME, CLI_CPF, CLI_EMAIL, CLI_TELEFONE)
VALUES ("Bruno Souza", "23456789011", "bruno.souza@example.com", "976543210");

INSERT INTO CLIENTE (CLI_NOME, CLI_CPF, CLI_EMAIL, CLI_TELEFONE)
VALUES ("Carla Mendes", "34567890122", "carla.mendes@example.com", "965432109");

INSERT INTO CLIENTE (CLI_NOME, CLI_CPF, CLI_EMAIL, CLI_TELEFONE)
VALUES ("Daniel Rocha", "20248215027", "daniel.rocha@example.com", "63918606245");

INSERT INTO CLIENTE (CLI_NOME, CLI_CPF, CLI_EMAIL, CLI_TELEFONE)
VALUES ("Elaine Costa", "77599082026", "elaine.costa@example.com", "22905268865");

INSERT INTO CLIENTE (CLI_NOME, CLI_CPF, CLI_EMAIL, CLI_TELEFONE)
VALUES ("Felipe Lima", "10681444088", "felipe.lima@example.com", "82903461949");

INSERT INTO CLIENTE (CLI_NOME, CLI_CPF, CLI_EMAIL, CLI_TELEFONE)
VALUES ("Giselle Martins", "61583142002", "giselle.martins@example.com", "43958557467");

INSERT INTO CLIENTE (CLI_NOME, CLI_CPF, CLI_EMAIL, CLI_TELEFONE)
VALUES ("Henrique Alves", "44881762087", "henrique.alves@example.com", "51904484033");

INSERT INTO CLIENTE (CLI_NOME, CLI_CPF, CLI_EMAIL, CLI_TELEFONE)
VALUES ("Isabela Ferreira", "25231643025", "isabela.ferreira@example.com", "13971102808");

INSERT INTO CLIENTE (CLI_NOME, CLI_CPF, CLI_EMAIL, CLI_TELEFONE)
VALUES ("João Oliveira", "32805008006", "joão.oliveira@example.com", "11993129941");

SELECT * FROM CLIENTE;

INSERT INTO PRODUTO (PRO_NOME, PRO_DESCRICAO, PRO_PRECO, PRO_QTD_DISPONIVEL)
VALUES 	("Jetta gli", "carro esportivo", "10.000", "5"),
		("Notebook Dell Inspiron", "Notebook com processador Intel Core i7, 16GB de RAM, 512GB SSD", "450", "10"),
        ("Smartphone Samsung Galaxy S21", "Smartphone com tela de 6.2 polegadas, 128GB de armazenamento", "350", "15"),
		("TV LG 55 4K ", "Smart TV com resolução 4K e HDR", "280", "8"),
        ("Drone DJI Phantom 4 ", "Drone com câmera 4K e estabilização de imagem", "300", "55"),
        ("Câm. Canon EOSI T7 ", "Camêra DSLR com lente 18-55mm,24.1MP", "250", "2"),
        ("Câmera GoPro Hero 9 ", "Câmera de ação com resolução 5K e resistência á água", "80", "60"),
        ("Tenda Eventos 5x5cm", "Tenda resistente á água e facíl de montar", "200", "4"),
        ("Microfone Shure SM58 ", "Microfone para apresentação e shows", "40", "35"),
        ("Mesa de Som Behringer", "Mesa de som com 16 canais e efeitos integrados", "500", "3"),
        ("Kit de Iluminação Fotográfica ", "Kit com softbox, tripés e lâmpadas de LED", "100", "6");
        
SELECT * FROM PRODUTO;
SELECT PRO_NOME, PRO_DESCRICAO FROM PRODUTO;
SELECT PRO_NOME, PRO_DESCRICAO, PRO_PRECO FROM PRODUTO;

-- SELECIONAR APENAS OS PRODUTOS COM PREÇO > 250
SELECT * 
FROM 	PRODUTO
WHERE	PRO_PRECO > 250;

-- SELECIONAR APENAS O PRODUTO DE ID = 3
SELECT PRO_ID, PRO_NOME
FROM PRODUTO
WHERE PRO_ID = 3;

-- SELECIONAR TODOS OS PRODUTOS QUE COMTÉM NOTBOOK EM QUALQUER PARTE DO NOME
SELECT * 
FROM PRODUTO 
WHERE PRO_NOME LIKE '%NOTEBOOK%';

-- ATUALIZAR A QUANTIDADE DE NOTBOOK PARA 200
UPDATE PRODUTO
SET PRO_QTD_DISPONIVEL = 200
WHERE	 PRO_ID = 4; -- UPDATE TEM QUE TER WHERE

-- ATUALIZAR A DESCRICAO DO NOTEBOOK PARA VAZIO
UPDATE PRODUTO
SET PRO_DESCRICAO = NULL 
WHERE PRO_ID = 4; -- UPDATE TEM QUE TER WHERE 

-- APAGAR (DELETAR UMA LINHA) O NOTEBOOK
DELETE FROM PRODUTO
WHERE PRO_ID = 4; -- DELETE TEM QUE TER WHERE

INSERT INTO ALUGUEL (ALU_DATA_ALUGUEL, ALU_DATA_DEVOLUCAO, ALU_VALOR_TOTAL, FK_CLI_ID)
VALUES ("2026-10-08", "2026-10-15", 500, 2);

SELECT * FROM ALUGUEL;

INSERT INTO ALUGUEL_PRODUTO (FK_PRO_ID, FK_ALU_ID)
VALUES (1,1);

SELECT * FROM ALUGUEL_PRODUTO;

