CREATE DATABASE IF NOT EXISTS BD_EST_SUPERMERCADO;
USE BD_EST_SUPERMERCADO; 

CREATE TABLE IF NOT EXISTS CATEGORIA(
ID INT AUTO_INCREMENT PRIMARY KEY,
TIPO VARCHAR(50),
NOME VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS FORNECEDOR(
	CPF_CNPJ VARCHAR(14) PRIMARY KEY,
    TELEFONE VARCHAR(9) NOT NULL,
	EMAIL VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUTOS(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    VALOR DOUBLE NOT NULL,
    DATA_VALIDADE DATE,
    FK_CATEGORIA INT,
    FOREIGN KEY (FK_CATEGORIA) REFERENCES CATEGORIA(ID)
);

CREATE TABLE IF NOT EXISTS FORNECEDOR_PRODUTOS(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    FK_CPF_CNPJ_FORNECEDOR VARCHAR(14),
    FK_ID_PRODUTO INT,
    FOREIGN KEY (FK_CPF_CNPJ_FORNECEDOR) REFERENCES FORNECEDOR(CPF_CNPJ),
	FOREIGN KEY (FK_ID_PRODUTO) REFERENCES PRODUTOS(ID)
);








