CREATE DATABASE IF NOT EXISTS BD_MUSICA;
USE BD_MUSICA; 

CREATE TABLE IF NOT EXISTS ARTISTA(
	CPF VARCHAR(11) PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    TELEFONE VARCHAR(9) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL
);
DROP TABLE CONSUMIDOR;
CREATE TABLE IF NOT EXISTS GENERO(
ID INT AUTO_INCREMENT PRIMARY KEY,
ESTILO VARCHAR(50) NOT NULL,
RITMO VARCHAR(50),
NOME VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS ALBUM(
ID INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(100) NOT NULL,
CAPA BLOB NOT NULL,
FAIXAS VARCHAR(50),
FK_CPF_ARTISTA VARCHAR(11),
FOREIGN KEY (FK_CPF_ARTISTA) REFERENCES ARTISTA(CPF)
);

CREATE TABLE IF NOT EXISTS FAIXA(
ID INT AUTO_INCREMENT PRIMARY KEY,
MUSICA VARCHAR(50),
NOME VARCHAR(100) NOT NULL,
CAPA BLOB NOT NULL,
FK_CPF_ALBUM INT,
FK_ID_GENERO INT,
FOREIGN KEY (FK_CPF_ALBUM) REFERENCES ALBUM(ID),
FOREIGN KEY (FK_ID_GENERO) REFERENCES GENERO(ID)
);







